// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod example {
        pub mod text_analysis {
            #[allow(dead_code, clippy::all)]
            pub mod analyzer {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub struct WordStats {
                    pub word: _rt::String,
                    pub count: u32,
                }
                impl ::core::fmt::Debug for WordStats {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("WordStats")
                            .field("word", &self.word)
                            .field("count", &self.count)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct AnalysisResult {
                    pub total_words: u32,
                    pub unique_words: u32,
                    pub top_words: _rt::Vec<WordStats>,
                }
                impl ::core::fmt::Debug for AnalysisResult {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("AnalysisResult")
                            .field("total-words", &self.total_words)
                            .field("unique-words", &self.unique_words)
                            .field("top-words", &self.top_words)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_analyze_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::analyze(_rt::string_lift(bytes0), arg2 as u32);
                    let ptr2 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let AnalysisResult {
                                total_words: total_words3,
                                unique_words: unique_words3,
                                top_words: top_words3,
                            } = e;
                            *ptr2.add(4).cast::<i32>() = _rt::as_i32(total_words3);
                            *ptr2.add(8).cast::<i32>() = _rt::as_i32(unique_words3);
                            let vec6 = top_words3;
                            let len6 = vec6.len();
                            let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec6.len() * 12,
                                4,
                            );
                            let result6 = if layout6.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout6);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec6.into_iter().enumerate() {
                                let base = result6.add(i * 12);
                                {
                                    let WordStats { word: word4, count: count4 } = e;
                                    let vec5 = (word4.into_bytes()).into_boxed_slice();
                                    let ptr5 = vec5.as_ptr().cast::<u8>();
                                    let len5 = vec5.len();
                                    ::core::mem::forget(vec5);
                                    *base.add(4).cast::<usize>() = len5;
                                    *base.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                                    *base.add(8).cast::<i32>() = _rt::as_i32(count4);
                                }
                            }
                            *ptr2.add(16).cast::<usize>() = len6;
                            *ptr2.add(12).cast::<*mut u8>() = result6;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec7 = (e.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr2.add(8).cast::<usize>() = len7;
                            *ptr2.add(4).cast::<*mut u8>() = ptr7.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_analyze<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(12).cast::<*mut u8>();
                            let l2 = *arg0.add(16).cast::<usize>();
                            let base5 = l1;
                            let len5 = l2;
                            for i in 0..len5 {
                                let base = base5.add(i * 12);
                                {
                                    let l3 = *base.add(0).cast::<*mut u8>();
                                    let l4 = *base.add(4).cast::<usize>();
                                    _rt::cabi_dealloc(l3, l4, 1);
                                }
                            }
                            _rt::cabi_dealloc(base5, len5 * 12, 4);
                        }
                        _ => {
                            let l6 = *arg0.add(4).cast::<*mut u8>();
                            let l7 = *arg0.add(8).cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn analyze(
                        text: _rt::String,
                        top_n: u32,
                    ) -> Result<AnalysisResult, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_example_text_analysis_analyzer_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[export_name =
                        "example:text-analysis/analyzer#analyze"] unsafe extern "C" fn
                        export_analyze(arg0 : * mut u8, arg1 : usize, arg2 : i32,) -> *
                        mut u8 { $($path_to_types)*:: _export_analyze_cabi::<$ty > (arg0,
                        arg1, arg2) } #[export_name =
                        "cabi_post_example:text-analysis/analyzer#analyze"] unsafe extern
                        "C" fn _post_return_analyze(arg0 : * mut u8,) {
                        $($path_to_types)*:: __post_return_analyze::<$ty > (arg0) } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_example_text_analysis_analyzer_cabi;
                #[repr(align(4))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 20]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 20],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_text_analyzer_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::example::text_analysis::analyzer::__export_example_text_analysis_analyzer_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::example::text_analysis::analyzer);
    };
}
#[doc(inline)]
pub(crate) use __export_text_analyzer_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:example:text-analysis:text-analyzer:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 349] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd9\x01\x01A\x02\x01\
A\x02\x01B\x08\x01r\x02\x04words\x05county\x04\0\x0aword-stats\x03\0\0\x01p\x01\x01\
r\x03\x0btotal-wordsy\x0cunique-wordsy\x09top-words\x02\x04\0\x0fanalysis-result\
\x03\0\x03\x01j\x01\x04\x01s\x01@\x02\x04texts\x05top-ny\0\x05\x04\0\x07analyze\x01\
\x06\x04\0\x1eexample:text-analysis/analyzer\x05\0\x04\0#example:text-analysis/t\
ext-analyzer\x04\0\x0b\x13\x01\0\x0dtext-analyzer\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.220.0\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
